name: widgetbook_size_inspector
description: A Widgetbook addon that provides accurate widget size inspection using RenderBox constraints
version: 0.0.1
homepage: https://github.com/seunghwanly/widgetbook_size_inspector
repository: https://github.com/seunghwanly/widgetbook_size_inspector
issue_tracker: https://github.com/seunghwanly/widgetbook_size_inspector/issues
documentation: https://github.com/seunghwanly/widgetbook_size_inspector/blob/main/README.md
maintainers:
  - name: seunghwanly
    email: seunghwanly@gmail.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
